// <auto-generated />
using System;
using KaraW3B.Server.Songs.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KaraW3B.Server.Songs.Core.Migrations
{
    [DbContext(typeof(KaraW3BDbContext))]
    [Migration("20260720142059_InitializeDatabase")]
    partial class InitializeDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("KaraW3B.Server.Songs.Core.Persistence.Models.Libraries.DbLibrary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnalyzing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastAnalyzeMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("KaraW3B.Server.Songs.Core.Persistence.Models.Songs.DbSong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalyzedFileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Audio")
                        .HasColumnType("TEXT");

                    b.Property<int>("AudioConversion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Background")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Bpm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cover")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Creators")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Editions")
                        .HasColumnType("TEXT");

                    b.Property<double?>("End")
                        .HasColumnType("REAL");

                    b.Property<double?>("Gap")
                        .HasColumnType("REAL");

                    b.PrimitiveCollection<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instrumental")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstrumentalConversion")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Languages")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastParseTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Medley")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("NotManagedHeaders")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PreviewStart")
                        .HasColumnType("REAL");

                    b.Property<string>("ProvidedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rendition")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SongFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Start")
                        .HasColumnType("REAL");

                    b.PrimitiveCollection<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.Property<string>("Video")
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoConversion")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("VideoGap")
                        .HasColumnType("REAL");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vocals")
                        .HasColumnType("TEXT");

                    b.Property<int>("VocalsConversion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("KaraW3B.Server.Songs.Core.Persistence.Models.Songs.DbSongAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FileLine")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.ToTable("SongAlerts");
                });

            modelBuilder.Entity("KaraW3B.Server.Songs.Core.Persistence.Models.Songs.DbSongNote", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FileLine")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoteType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Pitch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartBeat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("SongId", "FileLine");

                    b.HasIndex("PlayerNumber");

                    b.ToTable("SongNotes");
                });

            modelBuilder.Entity("KaraW3B.Server.Songs.Core.Persistence.Models.Songs.DbSongPlayer", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("SongId", "Number");

                    b.ToTable("SongPlayers");
                });

            modelBuilder.Entity("KaraW3B.Server.Songs.Core.Persistence.Models.Songs.DbSong", b =>
                {
                    b.HasOne("KaraW3B.Server.Songs.Core.Persistence.Models.Libraries.DbLibrary", "Library")
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("KaraW3B.Server.Songs.Core.Persistence.Models.Songs.DbSongAlert", b =>
                {
                    b.HasOne("KaraW3B.Server.Songs.Core.Persistence.Models.Songs.DbSong", "Song")
                        .WithMany("Alerts")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("KaraW3B.Server.Songs.Core.Persistence.Models.Songs.DbSongNote", b =>
                {
                    b.HasOne("KaraW3B.Server.Songs.Core.Persistence.Models.Songs.DbSong", "Song")
                        .WithMany("Notes")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("KaraW3B.Server.Songs.Core.Persistence.Models.Songs.DbSongPlayer", b =>
                {
                    b.HasOne("KaraW3B.Server.Songs.Core.Persistence.Models.Songs.DbSong", "Song")
                        .WithMany("Players")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("KaraW3B.Server.Songs.Core.Persistence.Models.Songs.DbSong", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Notes");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
