// <auto-generated />
using System;
using KaraWeb.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KaraWeb.Core.Migrations
{
    [DbContext(typeof(KaraWebDbContext))]
    [Migration("20260607204718_InitializeDatabase")]
    partial class InitializeDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("KaraWeb.Core.Persistence.Libraries.Library", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("KaraWeb.Core.Persistence.Songs.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalyzedFileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Audio")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Background")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundUrl")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Bpm")
                        .HasColumnType("REAL");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cover")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Editions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Encoding")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<int?>("End")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Gap")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instrumental")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRelative")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Languages")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MedleyEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MedleyStart")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("NotManagedHeaders")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreviewStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProvidedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rendition")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SongFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Start")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Video")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VideoGap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vocals")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("KaraWeb.Core.Persistence.Songs.SongAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.ToTable("SongAlerts");
                });

            modelBuilder.Entity("KaraWeb.Core.Persistence.Songs.SongNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Errors")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Pitch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartBeat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.ToTable("SongNotes");
                });

            modelBuilder.Entity("KaraWeb.Core.Persistence.Songs.SongPlayer", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("SongId", "Number");

                    b.ToTable("SongPlayers");
                });

            modelBuilder.Entity("KaraWeb.Core.Persistence.Songs.Song", b =>
                {
                    b.HasOne("KaraWeb.Core.Persistence.Libraries.Library", "Library")
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("KaraWeb.Core.Persistence.Songs.SongAlert", b =>
                {
                    b.HasOne("KaraWeb.Core.Persistence.Songs.Song", "Song")
                        .WithMany("Alerts")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("KaraWeb.Core.Persistence.Songs.SongNote", b =>
                {
                    b.HasOne("KaraWeb.Core.Persistence.Songs.Song", "Song")
                        .WithMany("Notes")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("KaraWeb.Core.Persistence.Songs.SongPlayer", b =>
                {
                    b.HasOne("KaraWeb.Core.Persistence.Songs.Song", "Song")
                        .WithMany("Players")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("KaraWeb.Core.Persistence.Songs.Song", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Notes");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
