name: Draft Changelog

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  draft-changelog:
    if: github.repository == 'KaraW3B/songs-server'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v7
